### ISSUE TITLE
[ERROR] Spacedeck is unreachable, it might not be running. cURL error 7: Failed to connect to localhost port 9666: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:9666/api/spaces

### ISSUE THREAD

**Issue by nooblag** [nextcloud/integration_whiteboard#36]
Getting some of these errors in the Nextcloud log:

[ERROR] Spacedeck is unreachable, it might not be running. cURL error 7: Failed to connect to localhost port 9666: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:9666/api/spaces

![Log](https://user-images.githubusercontent.com/1122344/122437157-ca605e00-cfdc-11eb-8d9e-a56df9e64f2d.PNG)

Whiteboard version:  0.0.14
Nextcloud version: 21.0.2
Server: Ubuntu 18.04 LTS, nginx 1.18.0, psql (PostgreSQL) 10.17 (Ubuntu 10.17-0ubuntu0.18.04.1)

**Comment by TimmiORG** [comment]
Hi,
I have the same also with Nextcloud 21.0.3.

**Comment by benhartwich** [comment]
Same issue in 22.0.

**Comment by TimmiORG** [comment]
Update: looks like this is an issue with SElinux. It is working if it is turned off.

**Comment by rondadon** [comment]
Yepp, same here with Nextcloud 22.1.0 Docker. Instead of opening the .whiteboard File in Spacedeck after clicking on it, the Browser Downloads the File.

**Comment by hendysama** [comment]
> Update: looks like this is an issue with SElinux. It is working if it is turned off.

I dare not do it

**Comment by nooblag** [comment]
Our system does not use SELinux, and yes, regardless, I would not turn that off.

**Comment by tcs-ulli** [comment]
any solutions for that in docker ?

**Comment by nooblag** [comment]
Perhaps this has been fixed with Nextcloud 22.2.0? I haven't seen this error since upgrading. Can others confirm?

**Comment by cue108** [comment]
Well, I see the error message among others in this wild-growing evolutionary diamond of software.

![image](https://user-images.githubusercontent.com/513984/141254624-5ec0fec6-268b-477c-86ee-add9f96ae2e6.png)

Version: 22.2.0

![image](https://user-images.githubusercontent.com/513984/141254983-bdd1b8fb-35a6-42f2-b7ac-61bc5ff9aabf.png)

I am using the official Docker Image

**Comment by blubbi321** [comment]
Same issue with the official snap

**Comment by pat-githubber** [comment]
@nooblag, I still cannot open `.whiteboard` files in NextCloudPi 22.2.3

**Comment by nooblag** [comment]
@pat-githubber You might need to look for another issue for that? This issue regards above cURL error only.

**Comment by geruto** [comment]
Same issue for my (large) customer. Are there any workarounds? Afaik it was still working in earlier NC22 versions.

**Comment by mjeshurun** [comment]
Same behavior for me, as OP described.
Running Nextcloud 23.0.2. Installed as a docker app on UnRAID 6.9.2.
